### ISSUE TITLE
Add support for FOSSASIA's open event JSON format

### ISSUE THREAD

**Issue by scandindian** [splitbrain/giraffe#11]
Currently the app displays the data parsed from iCal format. Although it is great but FOSSASIA's JSON format provides more information.
We could modify the app to enable the support for it too along with normal iCal data.

Here are some samples in open event format. https://github.com/fossasia/open-event

An organiser can easily create the event from the server and then import the data. It also provides alternative iCal link.

**Comment by splitbrain** [comment]
pr welcome

**Comment by scandindian** [comment]
@splitbrain Thanks for looking up. I will send pr in a while.
